dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1"

dotenv: .env

wallet:
  local_from_key: ${LOCAL_PRIVATE_KEY}
  online_from_key: ${GOERLI_PRIVATE_KEY}

networks:
  default: development
  goerli:
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
  ganache-local-1:
    verify: False